name: "Hello world workflow"

# Control when the action will run, triggers the workflow on push to the  master or production

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        run: echo "Hello world"

      - name: "print date"
        run: date

  multiply_action:
    if: ${{ github.ref_name == 'master' || github.ref_name == 'production'}}
    runs-on: ubuntu-latest
    steps:
      - name: "multiply 2 and 3"
        run: expr 2 \* 3

  workflow_dispatch:
    if: ${{github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: running on the pull request
        run: echo "workflow Running on the pull request"
